name: deploy

on:
  push:

permissions:
  contents: write

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python v3
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build docs
        run: mkdocs build

  deploy:
    name: Deploy on gh pages
    needs: [build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python v3
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Setup cache
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Deploy
        run: mkdocs gh-deploy --force --clean --verbose
